<label>Device type:
	<select name="devtype">		
		<option value="n">NMOS</option>			
		<option value="p">PMOS</option>					
	</select>
</label>

<label>BINUNIT:<input size="4" type="text" name="binunit" value="1"/></label>            <label>PARAMCHK:<input size="4" type="text" name="paramchk" value="1"/></label>            <label>MOBMOD:<input size="4" type="text" name="mobmod" value="0"/></label>          
<label>CAPMOD:<input size="4" type="text" name="capmod" value="1"/></label>            <label>IGCMOD:<input size="4" type="text" name="igcmod" value="1"/></label>            <label>IGBMOD:<input size="4" type="text" name="igbmod" value="1"/></label>            <label>GEOMOD:<input size="4" type="text" name="geomod" value="1"/></label>          
<label>DIOMOD:<input size="4" type="text" name="diomod" value="1"/></label>            <label>RDSMOD:<input size="4" type="text" name="rdsmod" value="0"/></label>            <label>RBODYMOD:<input size="4" type="text" name="rbodymod" value="0"/></label>            <label>RGATEMOD:<input size="4" type="text" name="rgatemod" value="1"/></label>          
<label>PERMOD:<input size="4" type="text" name="permod" value="1"/></label>            <label>ACNQSMOD:<input size="4" type="text" name="acnqsmod" value="0"/></label>            <label>TRNQSMOD:<input size="4" type="text" name="trnqsmod" value="0"/></label>            <label>TEMPMOD:<input size="4" type="text" name="tempmod" value="0"/></label>
<label>MTRLMOD:<input size="4" type="text" name="mtrlmod" value="1"/></label>		<label>CVCHARGEMOD:<input size="4" type="text" name="cvchargemod" value="0"/></label>

<label>EOT:<input size="4" type="text" name="eot" value="1.8E-009"/></label>		<label>VDDEOT:<input size="4" type="text" name="vddeot" value="1.5"/></label>	       <label>ADOS:<input size="4" type="text" name="ados" value="1.1"/></label>	      <label>BDOS:<input size="4" type="text" name="bdos" value="1.0"/></label>
<label>TNOM:<input size="4" type="text" name="tnom" value="27"/></label>           <label>TOXE:<input size="4" type="text" name="toxe" value="1.8E-009"/></label>     <label>TOXP:<input size="4" type="text" name="toxp" value="10E-010"/></label>      <label>TOXM:<input size="4" type="text" name="toxm" value="1.8E-009"/></label>   
<label>DTOX:<input size="4" type="text" name="dtox" value="8E-10"/></label>        <label>EPSROX:<input size="4" type="text" name="epsrox" value="3.9"/></label>          <label>WINT:<input size="4" type="text" name="wint" value="5E-009"/></label>       <label>LINT:<input size="4" type="text" name="lint" value="1E-009"/></label>   
<label>LL:<input size="4" type="text" name="ll" value="0"/></label>            <label>WL:<input size="4" type="text" name="wl" value="0"/></label>            <label>LLN:<input size="4" type="text" name="lln" value="1"/></label>            <label>WLN:<input size="4" type="text" name="wln" value="1"/></label>          
<label>LW:<input size="4" type="text" name="lw" value="0"/></label>            <label>WW:<input size="4" type="text" name="ww" value="0"/></label>            <label>LWN:<input size="4" type="text" name="lwn" value="1"/></label>            <label>WWN:<input size="4" type="text" name="wwn" value="1"/></label>          
<label>LWL:<input size="4" type="text" name="lwl" value="0"/></label>            <label>WWL:<input size="4" type="text" name="wwl" value="0"/></label>            <label>XPART:<input size="4" type="text" name="xpart" value="1"/></label>            <label>TOXREF:<input size="4" type="text" name="toxref" value="1.4E-009"/></label>   

<label>PHIG:<input size="4" type="text" name="phig" value="4.05"/></label>		<label>EPSRGATE:<input size="4" type="text" name="epsrgate" value="11.7"/></label>

<label>SAREF:<input size="4" type="text" name="saref" value="5E-6"/></label>         <label>SBREF:<input size="4" type="text" name="sbref" value="5E-6"/></label>         <label>WLOD:<input size="4" type="text" name="wlod" value="2E-6"/></label>         <label>KU0:<input size="4" type="text" name="ku0" value="-4E-6"/></label>
<label>KVSAT:<input size="4" type="text" name="kvsat" value="0.2"/></label>          <label>KVTH0:<input size="4" type="text" name="kvth0" value="-2E-8"/></label>        <label>TKU0:<input size="4" type="text" name="tku0" value="0.0"/></label>          <label>LLODKU0:<input size="4" type="text" name="llodku0" value="1.1"/></label> 
<label>WLODKU0:<input size="4" type="text" name="wlodku0" value="1.1"/></label>          <label>LLODVTH:<input size="4" type="text" name="llodvth" value="1.0"/></label>  	       <label>WLODVTH:<input size="4" type="text" name="wlodvth" value="1.0"/></label> 	      <label>LKU0:<input size="4" type="text" name="lku0" value="1E-6"/></label>  
<label>WKU0:<input size="4" type="text" name="wku0" value="1E-6"/></label>  	<label>PKU0:<input size="4" type="text" name="pku0" value="0.0"/></label>  	       <label>LKVTH0:<input size="4" type="text" name="lkvth0" value="1.1E-6"/></label>       <label>WKVTH0:<input size="4" type="text" name="wkvth0" value="1.1E-6"/></label>   
<label>PKVTH0:<input size="4" type="text" name="pkvth0" value="0.0"/></label>  	<label>STK2:<input size="4" type="text" name="stk2" value="0.0"/></label>          <label>LODK2:<input size="4" type="text" name="lodk2" value="1.0"/></label>          <label>STETA0:<input size="4" type="text" name="steta0" value="0.0"/></label>  
<label>LODETA0:<input size="4" type="text" name="lodeta0" value="1.0"/></label>		
<label>LAMBDA:<input size="4" type="text" name="lambda" value="4E-10"/></label>
<label>VSAT:<input size="4" type="text" name="vsat" value="1.1E+005"/></label>     
<label>VTL:<input size="4" type="text" name="vtl" value="2.0E5"/></label> 	<label>XN:<input size="4" type="text" name="xn" value="6.0"/></label> 	       <label>LC:<input size="4" type="text" name="lc" value="5E-9"/></label> 
<label>RNOIA:<input size="4" type="text" name="rnoia" value="0.577"/></label> 	<label>RNOIB:<input size="4" type="text" name="rnoib" value="0.37"/></label>
<label>LINTNOI:<input size="4" type="text" name="lintnoi" value="1E-009"/></label>
<label>TVOFF:<input size="4" type="text" name="tvoff" value="0.0"/></label>		<label>TVFBSDOFF:<input size="4" type="text" name="tvfbsdoff" value="0.0"/></label>
<label>VTH0:<input size="4" type="text" name="vth0" value="0.25"/></label>         
<label>K1:<input size="4" type="text" name="k1" value="0.35"/></label>         <label>K2:<input size="4" type="text" name="k2" value="0.05"/></label>         <label>K3:<input size="4" type="text" name="k3" value="0"/></label>          
<label>K3B:<input size="4" type="text" name="k3b" value="0"/></label>            <label>W0:<input size="4" type="text" name="w0" value="2.5E-006"/></label>     <label>DVT0:<input size="4" type="text" name="dvt0" value="1.8"/></label>          <label>DVT1:<input size="4" type="text" name="dvt1" value="0.52"/></label>       
<label>DVT2:<input size="4" type="text" name="dvt2" value="-0.032"/></label>       <label>DVT0W:<input size="4" type="text" name="dvt0w" value="0"/></label>            <label>DVT1W:<input size="4" type="text" name="dvt1w" value="0"/></label>            <label>DVT2W:<input size="4" type="text" name="dvt2w" value="0"/></label>          
<label>DSUB:<input size="4" type="text" name="dsub" value="2"/></label>            <label>MINV:<input size="4" type="text" name="minv" value="0.05"/></label>         <label>VOFFL:<input size="4" type="text" name="voffl" value="0"/></label>            <label>DVTP0:<input size="4" type="text" name="dvtp0" value="1E-007"/></label> 
<label>MINVCV:<input size="4" type="text" name="minvcv" value="2"/></label>		<label>VOFFCVL:<input size="4" type="text" name="voffcvl" value="0"/></label>    
<label>DVTP1:<input size="4" type="text" name="dvtp1" value="0.05"/></label>         <label>LPE0:<input size="4" type="text" name="lpe0" value="5.75E-008"/></label>    <label>LPEB:<input size="4" type="text" name="lpeb" value="2.3E-010"/></label>     <label>XJ:<input size="4" type="text" name="xj" value="2E-008"/></label>     
<label>NGATE:<input size="4" type="text" name="ngate" value="5E+020"/></label>       <label>NDEP:<input size="4" type="text" name="ndep" value="2.8E+018"/></label>     <label>NSD:<input size="4" type="text" name="nsd" value="1E+020"/></label>       <label>PHIN:<input size="4" type="text" name="phin" value="0"/></label>          
<label>CDSC:<input size="4" type="text" name="cdsc" value="0.0002"/></label>       <label>CDSCB:<input size="4" type="text" name="cdscb" value="0"/></label>            <label>CDSCD:<input size="4" type="text" name="cdscd" value="0"/></label>            <label>CIT:<input size="4" type="text" name="cit" value="0"/></label>          
<label>VOFF:<input size="4" type="text" name="voff" value="-0.15"/></label>        <label>NFACTOR:<input size="4" type="text" name="nfactor" value="1.2"/></label>          <label>ETA0:<input size="4" type="text" name="eta0" value="0.05"/></label>         <label>ETAB:<input size="4" type="text" name="etab" value="0"/></label>          
<label>UC:<input size="4" type="text" name="uc" value="-3E-011"/></label>      
<label>VFB:<input size="4" type="text" name="vfb" value="-0.55"/></label>        <label>U0:<input size="4" type="text" name="u0" value="0.032"/></label>        <label>UA:<input size="4" type="text" name="ua" value="5.0E-011"/></label>     <label>UB:<input size="4" type="text" name="ub" value="3.5E-018"/></label>   
<label>A0:<input size="4" type="text" name="a0" value="2"/></label>            <label>AGS:<input size="4" type="text" name="ags" value="1E-020"/></label>     
<label>A1:<input size="4" type="text" name="a1" value="0"/></label>            <label>A2:<input size="4" type="text" name="a2" value="1"/></label>            <label>B0:<input size="4" type="text" name="b0" value="-1E-020"/></label>      <label>B1:<input size="4" type="text" name="b1m" value="0"/></label>          
<label>KETA:<input size="4" type="text" name="keta" value="0.04"/></label>         <label>DWG:<input size="4" type="text" name="dwg" value="0"/></label>            <label>DWB:<input size="4" type="text" name="dwb" value="0"/></label>            <label>PCLM:<input size="4" type="text" name="pclm" value="0.08"/></label>      
<label>PDIBLC1:<input size="4" type="text" name="pdiblc1" value="0.028"/></label>        <label>PDIBLC2:<input size="4" type="text" name="pdiblc2" value="0.022"/></label>        <label>PDIBLCB:<input size="4" type="text" name="pdiblcb" value="-0.005"/></label>       <label>DROUT:<input size="4" type="text" name="drout" value="0.45"/></label>       
<label>PVAG:<input size="4" type="text" name="pvag" value="1E-020"/></label>       <label>DELTA:<input size="4" type="text" name="delta" value="0.01"/></label>         <label>PSCBE1:<input size="4" type="text" name="pscbe1" value="8.14E+008"/></label>    <label>PSCBE2:<input size="4" type="text" name="pscbe2" value="5E-008"/></label>     
<label>FPROUT:<input size="4" type="text" name="fprout" value="0.2"/></label>          <label>PDITS:<input size="4" type="text" name="pdits" value="0.2"/></label>          <label>PDITSD:<input size="4" type="text" name="pditsd" value="0.23"/></label>         <label>PDITSL:<input size="4" type="text" name="pditsl" value="2.3E+006"/></label>   
<label>RSH:<input size="4" type="text" name="rsh" value="0"/></label>            <label>RDSW:<input size="4" type="text" name="rdsw" value="50"/></label>           <label>RSW:<input size="4" type="text" name="rsw" value="50"/></label>           <label>RDW:<input size="4" type="text" name="rdw" value="50"/></label>        
<label>RDSWMIN:<input size="4" type="text" name="rdswmin" value="0"/></label>            <label>RDWMIN:<input size="4" type="text" name="rdwmin" value="0"/></label>            <label>RSWMIN:<input size="4" type="text" name="rswmin" value="0"/></label>            <label>PRWG:<input size="4" type="text" name="prwg" value="0"/></label>          
<label>PRWB:<input size="4" type="text" name="prwb" value="6.8E-011"/></label>     <label>WR:<input size="4" type="text" name="wr" value="1"/></label>            <label>ALPHA0:<input size="4" type="text" name="alpha0" value="0.074"/></label>        <label>ALPHA1:<input size="4" type="text" name="alpha1" value="0.005"/></label>      
<label>BETA0:<input size="4" type="text" name="beta0" value="30"/></label>           <label>AGIDL:<input size="4" type="text" name="agidl" value="0.0001"/></label>       <label>BGIDL:<input size="4" type="text" name="bgidl" value="2.1E+009"/></label>     <label>CGIDL:<input size="4" type="text" name="cgidl" value="0.0001"/></label>     
<label>EGIDL:<input size="4" type="text" name="egidl" value="0.8"/></label>          <label>AGISL:<input size="4" type="text" name="agisl" value="0.0002"/></label>       <label>BGISL:<input size="4" type="text" name="bgisl" value="2.1E+009"/></label>     <label>CGISL:<input size="4" type="text" name="cgisl" value="0.0002"/></label>
<label>EGISL:<input size="4" type="text" name="egisl" value="0.8"/></label>

<label>AIGBACC:<input size="4" type="text" name="aigbacc" value="0.012"/></label>        <label>BIGBACC:<input size="4" type="text" name="bigbacc" value="0.0028"/></label>       <label>CIGBACC:<input size="4" type="text" name="cigbacc" value="0.002"/></label>
<label>NIGBACC:<input size="4" type="text" name="nigbacc" value="1"/></label>            <label>AIGBINV:<input size="4" type="text" name="aigbinv" value="0.014"/></label>        <label>BIGBINV:<input size="4" type="text" name="bigbinv" value="0.004"/></label>        <label>CIGBINV:<input size="4" type="text" name="cigbinv" value="0.004"/></label>
<label>EIGBINV:<input size="4" type="text" name="eigbinv" value="1.1"/></label>          <label>NIGBINV:<input size="4" type="text" name="nigbinv" value="3"/></label>            <label>AIGC:<input size="4" type="text" name="aigc" value="0.012"/></label>        <label>BIGC:<input size="4" type="text" name="bigc" value="0.0028"/></label>
<label>CIGC:<input size="4" type="text" name="cigc" value="0.002"/></label>        <label>AIGS:<input size="4" type="text" name="aigs" value="0.012"/></label>        <label>BIGS:<input size="4" type="text" name="bigs" value="0.0028"/></label>       <label>CIGS:<input size="4" type="text" name="cigs" value="0.002"/></label>
<label>NIGC:<input size="4" type="text" name="nigc" value="1"/></label>            <label>POXEDGE:<input size="4" type="text" name="poxedge" value="1"/></label>            <label>PIGCD:<input size="4" type="text" name="pigcd" value="1"/></label>            <label>NTOX:<input size="4" type="text" name="ntox" value="1"/></label>
<label>AIGD:<input size="4" type="text" name="aigd" value="0.01"/></label>		<label>BIGD:<input size="4" type="text" name="bigd" value="0.003"/></label>	       <label>CIGD:<input size="4" type="text" name="cigd" value="0.0015"/></label> 

<label>XRCRG1:<input size="4" type="text" name="xrcrg1" value="12"/></label>           <label>XRCRG2:<input size="4" type="text" name="xrcrg2" value="5"/></label>          
<label>CGSO:<input size="4" type="text" name="cgso" value="6.238E-010"/></label>   <label>CGDO:<input size="4" type="text" name="cgdo" value="6.238E-010"/></label>   <label>CGBO:<input size="4" type="text" name="cgbo" value="2.56E-011"/></label>    <label>CGDL:<input size="4" type="text" name="cgdl" value="2.495E-10"/></label>     
<label>CGSL:<input size="4" type="text" name="cgsl" value="2.495E-10"/></label>    <label>CKAPPAS:<input size="4" type="text" name="ckappas" value="0.03"/></label>         <label>CKAPPAD:<input size="4" type="text" name="ckappad" value="0.03"/></label>         <label>ACDE:<input size="4" type="text" name="acde" value="1"/></label>          
<label>MOIN:<input size="4" type="text" name="moin" value="15"/></label>           <label>NOFF:<input size="4" type="text" name="noff" value="0.9"/></label>          <label>VOFFCV:<input size="4" type="text" name="voffcv" value="-0.02"/></label>

<label>KT1:<input size="4" type="text" name="kt1" value="-0.37"/></label>        <label>KT1L:<input size="4" type="text" name="kt1l" value="0.0"/></label>           <label>KT2:<input size="4" type="text" name="kt2" value="-0.042"/></label>       <label>UTE:<input size="4" type="text" name="ute" value="-1.5"/></label>
<label>UA1:<input size="4" type="text" name="ua1" value="1E-009"/></label>       <label>UB1:<input size="4" type="text" name="ub1" value="-3.5E-019"/></label>     <label>UC1:<input size="4" type="text" name="uc1" value="0"/></label>            <label>PRT:<input size="4" type="text" name="prt" value="0"/></label>
<label>AT:<input size="4" type="text" name="at" value="53000"/></label>

<label>FNOIMOD:<input size="4" type="text" name="fnoimod" value="1"/></label>            <label>TNOIMOD:<input size="4" type="text" name="tnoimod" value="0"/></label>          

<label>JSS:<input size="4" type="text" name="jss" value="0.0001"/></label>       <label>JSWS:<input size="4" type="text" name="jsws" value="1E-011"/></label>       <label>JSWGS:<input size="4" type="text" name="jswgs" value="1E-010"/></label>       <label>NJS:<input size="4" type="text" name="njs" value="1"/></label>          
<label>IJTHSFWD:<input size="4" type="text" name="ijthsfwd" value="0.01"/></label>         <label>IJTHSREV:<input size="4" type="text" name="ijthsrev" value="0.001"/></label>        <label>BVS:<input size="4" type="text" name="bvs" value="10"/></label>           <label>XJBVS:<input size="4" type="text" name="xjbvs" value="1"/></label>          
<label>JSD:<input size="4" type="text" name="jsd" value="0.0001"/></label>       <label>JSWD:<input size="4" type="text" name="jswd" value="1E-011"/></label>       <label>JSWGD:<input size="4" type="text" name="jswgd" value="1E-010"/></label>       <label>NJD:<input size="4" type="text" name="njd" value="1"/></label>          
<label>IJTHDFWD:<input size="4" type="text" name="ijthdfwd" value="0.01"/></label>         <label>IJTHDREV:<input size="4" type="text" name="ijthdrev" value="0.001"/></label>        <label>BVD:<input size="4" type="text" name="bvd" value="10"/></label>           <label>XJBVD:<input size="4" type="text" name="xjbvd" value="1"/></label>          
<label>PBS:<input size="4" type="text" name="pbs" value="1"/></label>            <label>CJS:<input size="4" type="text" name="cjs" value="0.0005"/></label>       <label>MJS:<input size="4" type="text" name="mjs" value="0.5"/></label>          <label>PBSWS:<input size="4" type="text" name="pbsws" value="1"/></label>          
<label>CJSWS:<input size="4" type="text" name="cjsws" value="5E-010"/></label>       <label>MJSWS:<input size="4" type="text" name="mjsws" value="0.33"/></label>         <label>PBSWGS:<input size="4" type="text" name="pbswgs" value="1"/></label>            <label>CJSWGS:<input size="4" type="text" name="cjswgs" value="3E-010"/></label>     
<label>MJSWGS:<input size="4" type="text" name="mjswgs" value="0.33"/></label>         <label>PBD:<input size="4" type="text" name="pbd" value="1"/></label>            <label>CJD:<input size="4" type="text" name="cjd" value="0.0005"/></label>       <label>MJD:<input size="4" type="text" name="mjd" value="0.5"/></label>        
<label>PBSWD:<input size="4" type="text" name="pbswd" value="1"/></label>            <label>CJSWD:<input size="4" type="text" name="cjswd" value="5E-010"/></label>       <label>MJSWD:<input size="4" type="text" name="mjswd" value="0.33"/></label>         <label>PBSWGD:<input size="4" type="text" name="pbswgd" value="1"/></label>          
<label>CJSWGD:<input size="4" type="text" name="cjswgd" value="5E-010"/></label>       <label>MJSWGD:<input size="4" type="text" name="mjswgd" value="0.33"/></label>         <label>TPB:<input size="4" type="text" name="tpb" value="0.005"/></label>        <label>TCJ:<input size="4" type="text" name="tcj" value="0.001"/></label>      
<label>TPBSW:<input size="4" type="text" name="tpbsw" value="0.005"/></label>        <label>TCJSW:<input size="4" type="text" name="tcjsw" value="0.001"/></label>        <label>TPBSWG:<input size="4" type="text" name="tpbswg" value="0.005"/></label>        <label>TCJSWG:<input size="4" type="text" name="tcjswg" value="0.001"/></label>      
<label>XTIS:<input size="4" type="text" name="xtis" value="3"/></label>            <label>XTID:<input size="4" type="text" name="xtid" value="3"/></label>          

<label>DMCG:<input size="4" type="text" name="dmcg" value="0E-006"/></label>       <label>DMCI:<input size="4" type="text" name="dmci" value="0E-006"/></label>       <label>DMDG:<input size="4" type="text" name="dmdg" value="0E-006"/></label>       <label>DMCGT:<input size="4" type="text" name="dmcgt" value="0E-007"/></label>     
<label>DWJ:<input size="4" type="text" name="dwj" value="0.0E-008"/></label>     <label>XGW:<input size="4" type="text" name="xgw" value="0E-007"/></label>       <label>XGL:<input size="4" type="text" name="xgl" value="0E-008"/></label>     

<label>RSHG:<input size="4" type="text" name="rshg" value="0.4"/></label>          <label>GBMIN:<input size="4" type="text" name="gbmin" value="1E-010"/></label>       <label>RBPB:<input size="4" type="text" name="rbpb" value="5"/></label>            <label>RBPD:<input size="4" type="text" name="rbpd" value="15"/></label>         
<label>RBPS:<input size="4" type="text" name="rbps" value="15"/></label>           <label>RBDB:<input size="4" type="text" name="rbdb" value="15"/></label>           <label>RBSB:<input size="4" type="text" name="rbsb" value="15"/></label>           <label>NGCON:<input size="4" type="text" name="ngcon" value="1"/></label>          

<label>JTSS:<input size="4" type="text" name="jtss" value="1E-4"/></label>         <label>JTSD:<input size="4" type="text" name="jtsd" value="1E-4"/></label>         <label>JTSSWS:<input size="4" type="text" name="jtssws" value="1E-10"/></label>        <label>JTSSWD:<input size="4" type="text" name="jtsswd" value="1E-10"/></label>
<label>JTSSWGS:<input size="4" type="text" name="jtsswgs" value="1E-7"/></label>         <label>JTSSWGD:<input size="4" type="text" name="jtsswgd" value="1E-7"/></label>
<label>NJTS:<input size="4" type="text" name="njts" value="20.0"/></label>         <label>NJTSSW:<input size="4" type="text" name="njtssw" value="15"/></label>           <label>NJTSSWG:<input size="4" type="text" name="njtsswg" value="6"/></label>            <label>VTSS:<input size="4" type="text" name="vtss" value="10"/></label>
<label>VTSD:<input size="4" type="text" name="vtsd" value="10"/></label>           <label>VTSSWS:<input size="4" type="text" name="vtssws" value="10"/></label>           <label>VTSSWD:<input size="4" type="text" name="vtsswd" value="10"/></label>
<label>NJTSD:<input size="4" type="text" name="njtsd" value="15.0"/></label>         <label>NJTSSWD:<input size="4" type="text" name="njtsswd" value="20"/></label>          <label>NJTSSWGD:<input size="4" type="text" name="njtsswgd" value="6"/></label>
<label>TNJTS:<input size="4" type="text" name="tnjts" value="0.1"/></label>          <label>TNJTSD:<input size="4" type="text" name="tnjtsd" value="0.05"/></label>
<label>VTSSWGS:<input size="4" type="text" name="vtsswgs" value="2"/></label> <label>VTSSWGD:<input size="4" type="text" name="vtsswgd" value="2"/></label>
<label>XTSS:<input size="4" type="text" name="xtss" value="0.02"/></label> <label>XTSD:<input size="4" type="text" name="xtsd" value="0.02"/></label> <label>XTSSWS:<input size="4" type="text" name="xtssws" value="0.02"/></label> <label>XTSSWD:<input size="4" type="text" name="xtsswd" value="0.02"/></label> <label>XTSSWGS:<input size="4" type="text" name="xtsswgs" value="0.02"/></label> <label>XTSSWGD:<input size="4" type="text" name="xtsswgd" value="0.02"/></label>


