<p>The oTFT compact models are aimed to support the bias enhancement of the charge carrier mobility and the significant contact effect in organic thin-film transistors (OTFTs). The oTFT compact model level 2 also supports other effects, such as channel conductance
    modulation (analogous to the channel length modulation in MOS transistors) and Ohmic and non-linear leakages. The distinct difference between TFT models and models for crystalline semiconductor field-effect transistors is that the mobility μ in TFT
    increases at higher bias as a power-law function
</p>
<p>
    <img src="<?php echo base_url('images/simulation/otft3eqt.png');?>" />
</p>
<p>
    where the mobility enhancement factor γ>0 (gamma in the oTFT compact model) is in the exponent of the power-law function, and μo is a known value of the mobility at given overdrive voltage Vγ.
</p>
<p>
    The low-field mobility μo is denoted with “uo” in the oTFT compact model, and μo and Vγ are model parameters. VG stands for gate bias voltage and the threshold voltage VT of the OTFT is also a parameter in the oTFT compact model. The oTFT model is a “mirror”
    of the OTFT structure as depicted in the figure. Conceptually, the oTFT model is arranged so that the sub-model components can be changed, replaced, removed or upgraded, as the needs evolve. The oTFT model is hierarchical. The top hierarchical level
    is module oTFT, in which there are “rails” for interconnection of the sub-models and instantiations of the sub-models between the rails. The “rails” are:
</p>
<p>
    1. Terminal nodes G, S and D for gate, source and drain, respectively. The oTFT model is connected in circuits by these nodes G, S and D;
</p>
<p>
    2. Intrinsic nodes GI, SI and DI. The semiconducting film of the OTFT is between SI and DI, and GI represents the interface of the gate dielectric with the gate conductor. Contact resistances and other terminal effects (such as geometric capacitances)
    are placed between rails S-SI, D-DI and G-GI. The intrinsic OTFT (semiconducting film and gate dielectric) is placed between the intrinsic nodes SI, DI, and GI;
</p>
<p>
    3.Control nodes GTS, GTD are conveying values of effective overdrive voltages. VGTS≈(VG−VT−VS) and VGTD≈(VG−VT−VD) are effective overdrive voltages at the source and drain ends of the intrinsic channel.
</p>
<p>
    These VGTS, VGTD are generated by a model for effective overdrive voltage, and VGTS, VGTD control many sub-model components, including the TFT generic charge drift DC model and the quasi-static charge model. VG, VS and VD are the potentials of the intrinsic
    nodes GI, SI, DI, and VT is the threshold voltage of the OTFT. The use of the control “rail” GTS, GTD makes the oTFT model symmetric and independent of the reference potential of electrical ground. The adoption of the above three “rails” provides
    advantages and convenience. For example, one clearly identifies sub-models for channel or for contacts, and can easily replace a sub-model (or even ignore it in simplifications during experimental characterizations), without destructing the behavior
    of the oTFT model. The “rails” also allow the sub-models to be simple, well related to physical interpretations and minimizes the number of model parameters and interferences between parameters. In fact, the oTFT model is a circuit with manageable
    components, instead of fixed “rigid” template of characteristic equations. The oTFT model is based on several publications on DC and quasi-static compact modeling of organic thin-film transistors (OTFTs).
</p>
<p>
    This implementation is coded in Verilog-A and can be regarded as level 2 of the oTFT compact models. The version of the model is oTFT 2.04.01 The Verilog-A code of the oTFT model and user manual for its use are available in [7]
</p>
